services:
    www:
        image: php:8.3.15-apache
        ports: 
            - 80:80
        volumes:
            - ./www:/var/www/html:rw
    db:
        image: mysql:8.0
        ports: 
            - 3306:3306
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_DATABASE: dbname
            MYSQL_USER: root
            MYSQL_PASSWORD: test
            MYSQL_ROOT_PASSWORD: test 
        volumes:
            - ./mysql/dump:/docker-entrypoint-initdb.d
            - ./mysql/conf:/etc/mysql/conf.d
            - ./mysql/db:/var/lib/mysql
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        ports:
            - 8000:80
        environment:
            MYSQL_USER: root
            MYSQL_PASSWORD: test
            MYSQL_ROOT_PASSWORD: test 