version: '3.9'
services:
  nginx:
    image: nginx
    volumes:
      - ./config/certbot/conf:/etc/letsencrypt
      - ./config/certbot/www:/var/www/certbot
      - ./config/default.conf:/etc/nginx/conf.d/default.conf
      - ./config/www:/usr/share/nginx/www
    restart: unless-stopped
    networks:
      - swarow
    ports:
      - 80:80
      - 443:443
networks:
  swarow:
    name: swarow
    attachable: true