version: '3.7'
services:
    registry:
        image: registry:2
        ports:
            -   5000:5000
            -   444:443
        volumes:
            -   "./certs:/certs"
        environment:
            -   REGISTRY_HTTP_ADDR=0.0.0.0:5000
        networks:
            -   backend
            -   proxy
            -   monitor
        deploy:
            placement:
                constraints:
                    -   node.role == manager
    swarmpit:
        image:  swarmpit/swarmpit:latest
        environment:
        -   SWARMPIT_DB=http://db:5984
        -   SWARMPIT_INFLUXDB=http://influxdb:8086
        volumes:
            -   /var/run/docker.sock:/var/run/docker.sock:ro
        ports:
            -   888:8080
        healthcheck:
            test:   ["CMD", "curl", "-f", "http://localhost:8080"]
            interval:   60s
            timeout:    10s
            retries:    3
        networks:
            -   monitor
        deploy:
            resources:
                limits:
                    cpus:   '0.50'
                    memory: 1024M
                reservations:
                    cpus:   '0.25'
                    memory: 512M
            placement:
                constraints:
                    -   node.role == manager
    db:
        image:  couchdb:2.3.0
        volumes:
            -   db-data:/opt/couchdb/data
        networks:
            -   monitor
        deploy:
            resources:
                limits:
                    cpus: '0.30'
                    memory: 256M
                reservations:
                    cpus: '0.15'
                    memory: 128M

    influxdb:
        image:  influxdb:1.7
        volumes:
            -   influx-data:/var/lib/influxdb
        networks:
            -   monitor
        deploy:
            resources:
                limits:
                    cpus:   '0.60'
                    memory: 512M
                reservations:
                    cpus:   '0.30'
                    memory: 128M
    agent:
        image:  swarmpit/agent:latest
        environment:
            -   EVENT_ENDPOINT=http://swarmpit:8080/events
            -   HEALTH_CHECK_ENDPOINT=http://swarmpit:8080/version
        volumes:
            -   /var/run/docker.sock:/var/run/docker.sock:ro
        networks:
            -   monitor
        deploy:
            mode:   global
            labels:
                swarmpit.agent: 'true'
            resources:
                limits:
                    cpus:   '0.10'
                    memory: 64M
                reservations:
                    cpus:   '0.05'
                    memory: 32M 

networks:
    monitor:
        name: monitor
        driver: overlay
        attachable: true
    proxy:
        name: proxy
        driver: overlay
        attachable: true
    backend:
        name: backend
        driver: overlay
        attachable: true
volumes:
    portainer_data:
    db-data:
        driver: local
    influx-data:
        driver: local